# Generated by Django 2.2 on 2020-06-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200608_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', 'timestamp']},
        ),
    ]
